### ISSUE TITLE
remove the -> <-

### ISSUE THREAD

**Issue by mat1jaczyyy** [Degura/Tetris-Community#4]
my eyes hurting

**Comment by Degura** [comment]
The -> <- is there to center the headers on Rentry. Unless you can figure out a way to keep them centered on Rentry while also making it work on GitHub, I can't remove them.

**Comment by Degura** [comment]
It'd meant to be read on Rentry yes. I wonder if it would be better to remove them in general so its more readable from the native .md format file (as different places read markdown different apparently lol). I personally think that centering the headers makes a little easier to parse through the file as centering = important (right? lol). I'll keep this open if someone else wants to add their opinion.

**Comment by Degura** [comment]
> ~oh whoops lord that is awful, let me undo my fork real quick to re-include this~
> 
> this should really be mentioned in the readme, this is not typical markdown behavior and kinda intrudes on that
> 
> centering isn't that important and is typically a style that can be applied elsewhere; this is... insanely clunky.
Heard. Ok, so what I will do is I will remember to add the arrows on Rentry. The markdown file on the repo will not have them for the sake of readability. I will note it on the readme.
